[project]
name = "2x2-ql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=3.0.4",
    "dash-bootstrap-components>=2.0.3",
    "h5py>=3.13.0",
    "hist[plot]>=2.8.1",
    "jupyter>=1.1.1",
    "k3d>=2.16.1",
    "kaleido>=1.0.0",
    "matplotlib>=3.10.1",
    "nbdime>=4.0.2",
    "numba>=0.61.2",
    "numpy>=2.2.5",
    "plotly>=6.1.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.45.0",
    "uproot>=5.6.1",
]
